repo: src/v8
patches:
-
  owners: codebytere
  file: add_realloc.patch
  description: |
    Blink overrides ArrayBuffer's allocator with its own one, while Node simply
    uses malloc and free, so we need to use v8's allocator in Node. As part of the
    10.6.0 upgrade, we needed to make SerializerDelegate accept an allocator
    argument in its constructor, and override ReallocateBufferMemory and
    FreeBufferMemory to use the allocator. We cannoy simply allocate and then memcpy
    when we override ReallocateBufferMemory, so we therefore need to implement
    Realloc on the v8 side.
-
  owners: alespergl
  file: build_gn.patch
  description: null
-
  owners: zcbenz
  file: array_buffer.patch
  description: null
-
  owners: zcbenz
  file: ostreams.patch
  description: null
-
  owners: alexeykuzmin,alespergl
  file: export_platform.patch
  description: |
    v8::Platform::SystemClockTimeMillis must be exported so that node::NodePlatform can call it
-
  owners: alespergl
  file: dcheck.patch
  description: null
-
  owners: nitsakh
  file: disable-warning-win.patch
  description:
    Disable unit test windows build warning
-
  owners: alexeykuzmin
  file: backport_b767cde1e7.patch
  description: Node 10.0.0 needs it.
-
  owners: alexeykuzmin
  file: backport_39d546a.patch
  description: Node 10.0.0 needs it.
-
  owners: alexeykuzmin
  file: backport_ff0a97933.patch
  description: Node 10.2.0 needs it.
-
  owners: alexeykuzmin
  file: backport_9fb02b526.patch
  description: Node 10.2.0 needs it.
-
  owners: alexeykuzmin
  file: backport_23652c5f.patch
  description: Node 10.2.0 needs it.
-
  owners: alexeykuzmin
  file: backport_b49206d.patch
  description: Node 10.2.0 needs it.
-
  owners: nitsakh
  file: backport_50206308.patch
  description: |
    Part (1/2) of backporting the array splice perf regression caused in ch66
-
  owners: nitsakh
  file: backport_2eb23a17.patch
  description: |
    Part (2/2) of backporting the array splice perf regression caused in ch66
